[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

baseURL = "https://example.com/" # change this before release #TODO
languageCode = "en-us" # change this before release #TODO
title = "My Hugo Site" # change this before release #TODO



favicon = "/media/img/misc/ico.ico"

[menu]
  [[menu.main]]
    name = "Home page"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3