[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

baseURL = "https://example.com/" # change this before release #TODO
languageCode = "en-us" # change this before release #TODO
title = "My Hugo Site" # change this before release #TODO



favicon = "/media/img/misc/ico.ico"