[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

baseURL = "https://example.com/"
languageCode = "en-us"
title = "My Hugo Site"
