name: Build Hugo and Store Artifact

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.160.0'
          extended: true

      - name: Build Hugo site
        run: hugo --minify --source page-framework --destination ../public

      - name: Debug public folder
        run: ls -l

      - name: Debug public folder 2
        run: |
          cd page-framework
          ls -l

      - name: Set timestamp
        id: timestamp
        run: echo "CURRENT_TIME=$(date '+%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Package output
        run: |
          if [ -d "public" ]; then
            ZIP_NAME="out-${CURRENT_TIME}.zip"
            zip -r "$ZIP_NAME" public
            echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          else
            echo "Error: public folder not found!"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site-${{ env.CURRENT_TIME }}
          path: ${{ env.ZIP_NAME }}